NinjaManager.Web/Models/Shop/BuySellModel.cs
namespace NinjaManager.Web.Models.Shop
{
    public class BuySellModel
    {
        public NinjaModel Ninja { get; set; }
        
        public GearModel Gear { get; set; }
        
        public class GearModel
        {
            public int Id { get; set; }

            public string Name { get; set; }

            public int Gold { get; set; }
        }
    }
}

NinjaManager.Web/Models/Shop/IndexModel.cs
using System.Collections.Generic;

namespace NinjaManager.Web.Models.Shop
{
    public class IndexModel
    {
        public Data.Models.Gear.GearCategory? Category { get; set; }

        public NinjaModel Ninja { get; set; }

        public IDictionary<Data.Models.Gear.GearCategory, IEnumerable<Gear>> Gears { get; set; }

        public class Gear
        {
            public int Id { get; set; }
            
            public string Name { get; set; }

            public int Gold { get; set; }
            
            public int Strength { get; set; }
            
            public int Agility { get; set; }
            
            public int Intelligence { get; set; }
            
            public GearState State { get; set; }

            public enum GearState
            {
                Bought,
                OwnsCategory,
                Expensive,
                Available
            }
        }
    }
}

NinjaManager.Web/Models/Shop/NinjaModel.cs
namespace NinjaManager.Web.Models.Shop
{
    public class NinjaModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int Gold { get; set; }
    }
}

NinjaManager.Web/Controllers/NinjasController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NinjaManager.Data.Models;
using NinjaManager.Data.Repositories;
using NinjaManager.Web.Models.Ninjas;

namespace NinjaManager.Web.Controllers
{
    public class NinjasController : Controller
    {
        private readonly NinjaRepository _ninjaRepository;

        public NinjasController(NinjaRepository ninjaRepository)
        {
            _ninjaRepository = ninjaRepository;
        }

        public async Task<IActionResult> Index()
        {
            var ninjas = await _ninjaRepository.GetAll();

            var model = new IndexModel
            {
                Ninjas = ninjas.Select(ninja => new IndexModel.Ninja
                {
                    Id = ninja.Id,
                    Name = ninja.Name,
                    Gold = ninja.Gold,
                    Gears = ninja.NinjaGears.Select(gear => gear.Gear.Name),
                })
            };

            return View(model);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var ninja = await _ninjaRepository.Get(id.Value);

            if (ninja == null)
            {
                return NotFound();
            }

            var model = new DetailsModel
            {
                Name = ninja.Name,
                Gold = ninja.Gold,
                Gears = ninja.NinjaGears.ToDictionary(ninjaGear => ninjaGear.Gear.Category, ninjaGear =>
                {
                    var gear = ninjaGear.Gear;

                    return new DetailsModel.Gear
                    {
                        Name = gear.Name,
                        Gold = gear.Gold,
                        Agility = gear.Agility,
                        Intelligence = gear.Intelligence,
                        Strength = gear.Strength,
                    };
                })
            };

            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost, ActionName("Create")]
        public async Task<IActionResult> CreatePost(CreateModel createModel)
        {
            if (ModelState.IsValid)
            {
                var ninja = new Ninja
                {
                    Name = createModel.Name,
                    Gold = 400
                };

                if (await _ninjaRepository.Create(ninja))
                {
                    return RedirectToAction(nameof(Index));
                }

                ModelState.AddModelError("", "The ninja could not be created.");
            }

            return View(createModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ninja = await _ninjaRepository.Get(id.Value);

            if (ninja == null)
            {
                return NotFound();
            }

            var model = new EditModel
            {
                Id = ninja.Id,
                Name = ninja.Name,
            };

            return View(model);
        }

        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditPost(EditModel editModel)
        {
            if (ModelState.IsValid)
            {
                var ninja = await _ninjaRepository.Get(editModel.Id);

                if (ninja == null)
                {
                    ModelState.AddModelError("", "The ninja does not exists");
                    return View(editModel);
                }

                ninja.Name = editModel.Name;

                if (await _ninjaRepository.Update(ninja))
                {
                    return RedirectToAction(nameof(Index));
                }

                ModelState.AddModelError("", "The ninja could not be edited.");
            }

            return View(editModel);
        }

        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ninja = await _ninjaRepository.Get(id.Value);

            if (ninja == null)
            {
                return NotFound();
            }

            var model = new DeleteModel
            {
                Id = ninja.Id,
                Name = ninja.Name,
                Gold = ninja.Gold,
                Gears = ninja.NinjaGears.Select(ninjaGear => ninjaGear.Gear.Name)
            };

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] = "Delete failed. Try again, and if the problem persists see your system administrator.";
            }

            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ninja = await _ninjaRepository.Get(id);

            if (ninja == null)
            {
                return RedirectToAction(nameof(Index));
            }

            ninja.NinjaGears.Clear();
            if (await _ninjaRepository.Delete(ninja))
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Delete), new {id, saveChangesError = true});
        }

        public async Task<IActionResult> Clear(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ninja = await _ninjaRepository.Get(id.Value);

            if (ninja == null)
            {
                return NotFound();
            }

            var model = new ClearModel
            {
                Id = ninja.Id,
                Name = ninja.Name,
                Gold = ninja.Gold,
                Gears = ninja.NinjaGears.Select(ninjaGear => new ClearModel.Gear
                {
                    Name = ninjaGear.Gear.Name,
                    Gold = ninjaGear.Gear.Gold
                })
            };

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] = "Could not clear inventory. Try again, and if the problem persists see your system administrator.";
            }

            return View(model);
        }

        [HttpPost, ActionName("Clear")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClearConfirmed(int id)
        {
            var ninja = await _ninjaRepository.Get(id);

            if (ninja == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var addedGold = ninja.NinjaGears.Sum(ninjaGear => ninjaGear.Gear.Gold);

            ninja.Gold += addedGold;
            ninja.NinjaGears.Clear();

            if (await _ninjaRepository.Update(ninja))
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Clear), new {id, saveChangesError = true});
        }
    }
}

NinjaManager.Web/Controllers/ShopController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NinjaManager.Data.Models;
using NinjaManager.Data.Repositories;
using NinjaManager.Web.Models.Shop;

namespace NinjaManager.Web.Controllers
{
    [Route("/Ninjas/Shop/{ninjaId:int}/{action=Index}/{id?}")]
    public class ShopController : Controller
    {
        private readonly NinjaRepository _ninjaRepository;
        private readonly GearsRepository _gearsRepository;

        public ShopController(NinjaRepository ninjaRepository, GearsRepository gearsRepository)
        {
            _ninjaRepository = ninjaRepository;
            _gearsRepository = gearsRepository;
        }

        // GET
        public async Task<IActionResult> Index(int ninjaId, Gear.GearCategory? category)
        {
            var ninja = await _ninjaRepository.Get(ninjaId);

            if (ninja == null)
            {
                return NotFound();
            }

            var gears = await _gearsRepository.GetAll();

            var model = new IndexModel
            {
                Category = category,
                Ninja = new NinjaModel
                {
                    Id = ninja.Id,
                    Name = ninja.Name,
                    Gold = ninja.Gold
                },
                Gears = gears.GroupBy(gear => gear.Category).ToDictionary(grouping => grouping.Key, grouping => grouping.Select(gear => new IndexModel.Gear
                {
                    Id = gear.Id,
                    Name = gear.Name,
                    Gold = gear.Gold,
                    Agility = gear.Agility,
                    Intelligence = gear.Intelligence,
                    Strength = gear.Strength,
                    State = GetGearState(ninja, gear, grouping)
                }))
            };

            return View(model);
        }

        public async Task<IActionResult> Buy(int ninjaId, int? id, bool? saveChangesError = false)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var ninja = await _ninjaRepository.Get(ninjaId);

            var gear = await _gearsRepository.Get(id.Value);

            if (ninja == null || gear == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] = "Purchase failed. Try again, and if the problem persists see your system administrator.";
            }
            else if (ninja.NinjaGears.Select(ninjaGear => ninjaGear.Gear.Category).Contains(gear.Category))
            {
                ViewData["ErrorMessage"] = $"You already own a {gear.Category}.";
            }
            else if (ninja.Gold < gear.Gold)
            {
                ViewData["ErrorMessage"] = "You dont have enough money to buy this.";
            }

            var model = new BuySellModel
            {
                Ninja = new NinjaModel
                {
                    Id = ninja.Id,
                    Name = ninja.Name,
                    Gold = ninja.Gold
                },
                Gear = new BuySellModel.GearModel
                {
                    Id = gear.Id,
                    Name = gear.Name,
                    Gold = gear.Gold
                }
            };

            return View(model);
        }

        [HttpPost, ActionName("Buy")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BuyConfirmed(int ninjaId, int id)
        {
            var ninja = await _ninjaRepository.Get(ninjaId);

            var gear = await _gearsRepository.Get(id);

            if (ninja == null || gear == null)
            {
                return RedirectToAction(nameof(Index), new {ninjaId});
            }

            if (ninja.NinjaGears.Select(ninjaGear => ninjaGear.Gear.Category).Contains(gear.Category) || ninja.Gold < gear.Gold)
            {
                return RedirectToAction(nameof(Buy), new {ninjaId, id, saveChangesError = true});
            }

            ninja.Gold -= gear.Gold;
            ninja.NinjaGears.Add(new NinjaGear
            {
                GearId = gear.Id
            });

            if (await _ninjaRepository.Update(ninja))
            {
                return RedirectToAction(nameof(Index), new {ninjaId});
            }

            return RedirectToAction(nameof(Buy), new {ninjaId, id, saveChangesError = true});
        }

        public async Task<IActionResult> Sell(int ninjaId, int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ninja = await _ninjaRepository.Get(ninjaId);

            if (ninja == null)
            {
                return NotFound();
            }

            var ninjaGear = ninja.NinjaGears.FirstOrDefault(ninjaGear1 => ninjaGear1.GearId == id);

            if (ninjaGear == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] = "Sell failed. Try again, and if the problem persists see your system administrator.";
            }

            return View(new BuySellModel
            {
                Ninja = new NinjaModel
                {
                    Id = ninja.Id,
                    Name = ninja.Name,
                    Gold = ninja.Gold
                },
                Gear = new BuySellModel.GearModel
                {
                    Id = ninjaGear.Gear.Id,
                    Name = ninjaGear.Gear.Name,
                    Gold = ninjaGear.Gear.Gold
                }
            });
        }

        [HttpPost, ActionName("Sell")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SellConfirmed(int ninjaId, int id)
        {
            var ninja = await _ninjaRepository.Get(ninjaId);

            if (ninja == null)
            {
                return RedirectToAction(nameof(Index), new {ninjaId});
            }

            var ninjaGear = ninja.NinjaGears.FirstOrDefault(ninjaGear1 => ninjaGear1.GearId == id);

            if (ninjaGear == null)
            {
                return RedirectToAction(nameof(Sell), new {ninjaId, id, saveChangesError = true});
            }

            ninja.Gold += ninjaGear.Gear.Gold;
            ninja.NinjaGears.Remove(ninjaGear);

            if (await _ninjaRepository.Update(ninja))
            {
                return RedirectToAction(nameof(Index), new {ninjaId});
            }

            return RedirectToAction(nameof(Sell), new {ninjaId, id, saveChangesError = true});
        }

        private IndexModel.Gear.GearState GetGearState(Ninja ninja, Gear gear, IEnumerable<Gear> otherGears)
        {
            if (ninja.NinjaGears.Exists(ninjaGear => ninjaGear.GearId == gear.Id))
            {
                return IndexModel.Gear.GearState.Bought;
            }

            if (ninja.NinjaGears.Select(ninjaGear => ninjaGear.GearId).Intersect(otherGears.Select(gear1 => gear1.Id)).Any())
            {
                return IndexModel.Gear.GearState.OwnsCategory;
            }

            if (ninja.Gold < gear.Gold)
            {
                return IndexModel.Gear.GearState.Expensive;
            }

            return IndexModel.Gear.GearState.Available;
        }
    }
}

NinjaManager.Web/Views/Shop/Buy.cshtml
@using NinjaManager.Web.Models.Shop

@model BuySellModel

@{
    ViewBag.Title = $"Buy {Model.Gear.Name}";
}

<h1>Buy @Model.Gear.Name</h1>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h3>Are you sure you want to buy @Model.Gear.Name for @Model.Ninja.Name?</h3>
<div>
    <h4>Ninja</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ninja.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ninja.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ninja.Gold)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ninja.Gold)
        </dd>
    </dl>

    <h4>Gear</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gear.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gear.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gear.Gold)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gear.Gold)
        </dd>
    </dl>

    <form asp-action="Buy">
        <input type="hidden" asp-for="Ninja.Id"/>
        <input type="hidden" asp-for="Gear.Id"/>
        <input type="submit" value="Buy" class="btn btn-danger"/> |
        <a asp-action="Index">Back to Shop</a>
    </form>
</div>

NinjaManager.Web/Views/Shop/Index.cshtml
@using NinjaManager.Web.Models.Shop

@model IndexModel

@{
    ViewBag.Title = $"Shop for {Model.Ninja.Name}";
}

<dl class="row">
    <dt class="col-sm-10">
        <h1>Shop for <a asp-controller="Ninjas" asp-action="Details" asp-route-id="@Model.Ninja.Id">@Model.Ninja.Name</a></h1>
    </dt>
    <dt class="col-sm-2">
        <form method="get" asp-action="Index" asp-route-ninjaId="@Model.Ninja.Id">
            <select class="form-control" name="category" onchange="this.form.submit();">
                <option value="ShowAll">Show all</option>
                @foreach (var category in Model.Gears.Keys)
                {
                    <option selected="@(Model.Category.HasValue && Model.Category.Value == category)" value="@category">@category</option>
                }
            </select>
        </form>
    </dt>
</dl>

<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Ninja.Gold)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Ninja.Gold)
    </dd>
</dl>


@foreach (var pair in Model.Gears)
{
    if (!Model.Category.HasValue || Model.Category.Value == pair.Key)
    {
        var gears = pair.Value;

        <h2>@pair.Key</h2>
        <table class="table">
            <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => gears.FirstOrDefault().Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => gears.FirstOrDefault().Gold)
                </th>
                <th>
                    @Html.DisplayNameFor(model => gears.FirstOrDefault().Strength)
                </th>
                <th>
                    @Html.DisplayNameFor(model => gears.FirstOrDefault().Agility)
                </th>
                <th>
                    @Html.DisplayNameFor(model => gears.FirstOrDefault().Intelligence)
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var gear in gears)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(model => gear.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(model => gear.Gold)
                    </td>
                    <td>
                        @Html.DisplayFor(model => gear.Strength)
                    </td>
                    <td>
                        @Html.DisplayFor(model => gear.Agility)
                    </td>
                    <td>
                        @Html.DisplayFor(model => gear.Intelligence)
                    </td>
                    <td>
                        @switch (gear.State)
                        {
                            case IndexModel.Gear.GearState.Bought:
                                <a asp-action="Sell" asp-route-ninjaId="@Model.Ninja.Id" asp-route-id="@gear.Id">Sell</a>
                                break;
                            case IndexModel.Gear.GearState.OwnsCategory:
                                <span>Already owns @pair.Key</span>
                                break;
                            case IndexModel.Gear.GearState.Expensive:
                                <span>Not enough money</span>
                                break;
                            case IndexModel.Gear.GearState.Available:
                                <a asp-action="Buy" asp-route-ninjaId="@Model.Ninja.Id" asp-route-id="@gear.Id">Buy</a>
                                break;
                        }
                    </td>
                </tr>
            }
            </tbody>
        </table>
    }
}

NinjaManager.Web/Views/Shop/Sell.cshtml
@using NinjaManager.Web.Models.Shop

@model BuySellModel

@{
    ViewBag.Title = $"Sell {Model.Gear.Name}";
}

<h1>Sell @Model.Gear.Name</h1>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h3>Are you sure you want to sell this gear?</h3>
<div>
    <h4>Ninja</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ninja.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ninja.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ninja.Gold)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ninja.Gold)
        </dd>
    </dl>

    <h4>Gear</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gear.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gear.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gear.Gold)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gear.Gold)
        </dd>
    </dl>

    <form asp-action="Sell">
        <input type="hidden" asp-for="Ninja.Id"/>
        <input type="hidden" asp-for="Gear.Id"/>
        <input type="submit" value="Sell" class="btn btn-danger"/> |
        <a asp-action="Index">Back to Shop</a>
    </form>
</div>