NinjaManager.Web/Models/Ninjas/ClearModel.cs
using System.Collections.Generic;

namespace NinjaManager.Web.Models.Ninjas
{
    public class ClearModel
    {
        public int Id { get; set; }
        
        public string Name { get; set; }

        public int Gold { get; set; }

        public IEnumerable<Gear> Gears { get; set; }
        
        public class Gear
        {
            public string Name { get; set; }

            public int Gold { get; set; }
        }
    }
}

NinjaManager.Web/Models/Ninjas/CreateModel.cs
using System.ComponentModel.DataAnnotations;

namespace NinjaManager.Web.Models.Ninjas
{
    public class CreateModel
    {
        [Required]
        public string Name { get; set; }
    }
}

NinjaManager.Web/Models/Ninjas/DeleteModel.cs
using System.Collections.Generic;

namespace NinjaManager.Web.Models.Ninjas
{
    public class DeleteModel
    {
        public int Id { get; set; }
        
        public string Name { get; set; }

        public int Gold { get; set; }

        public IEnumerable<string> Gears { get; set; }
    }
}

NinjaManager.Web/Models/Ninjas/DetailsModel.cs
using System.Collections.Generic;
using System.Linq;

namespace NinjaManager.Web.Models.Ninjas
{
    public class DetailsModel
    {
        public string Name { get; set; }

        public int Gold { get; set; }

        public IDictionary<Data.Models.Gear.GearCategory, Gear> Gears { get; set; }

        public KeyValuePair<Data.Models.Gear.GearCategory, Gear> GetGear(Data.Models.Gear.GearCategory category)
        {
            return Gears.ContainsKey(category) ? Gears.First(valuePair => valuePair.Key == category) : new KeyValuePair<Data.Models.Gear.GearCategory, Gear>(category, null);
        }

        public class Gear
        {
            public string Name { get; set; }
            
            public int Gold { get; set; }
            
            public int Strength { get; set; }

            public int Intelligence { get; set; }

            public int Agility { get; set; }
        }
    }
}

NinjaManager.Web/Models/Ninjas/EditModel.cs
using System.ComponentModel.DataAnnotations;

namespace NinjaManager.Web.Models.Ninjas
{
    public class EditModel : CreateModel
    {
        [Required]
        public int Id { get; set; }
    }
}

NinjaManager.Web/Models/Ninjas/IndexModel.cs
using System.Collections.Generic;

namespace NinjaManager.Web.Models.Ninjas
{
    public class IndexModel
    {
        public IEnumerable<Ninja> Ninjas { get; set; }

        public class Ninja
        {
            public int Id { get; set; }

            public string Name { get; set; }

            public int Gold { get; set; }

            public IEnumerable<string> Gears { get; set; }
        }
    }
}

NinjaManager.Web/Controllers/NinjasController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NinjaManager.Data.Models;
using NinjaManager.Data.Repositories;
using NinjaManager.Web.Models.Ninjas;

namespace NinjaManager.Web.Controllers
{
    public class NinjasController : Controller
    {
        private readonly NinjaRepository _ninjaRepository;

        public NinjasController(NinjaRepository ninjaRepository)
        {
            _ninjaRepository = ninjaRepository;
        }

        public async Task<IActionResult> Index()
        {
            var ninjas = await _ninjaRepository.GetAll();

            var model = new IndexModel
            {
                Ninjas = ninjas.Select(ninja => new IndexModel.Ninja
                {
                    Id = ninja.Id,
                    Name = ninja.Name,
                    Gold = ninja.Gold,
                    Gears = ninja.NinjaGears.Select(gear => gear.Gear.Name),
                })
            };

            return View(model);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var ninja = await _ninjaRepository.Get(id.Value);

            if (ninja == null)
            {
                return NotFound();
            }

            var model = new DetailsModel
            {
                Name = ninja.Name,
                Gold = ninja.Gold,
                Gears = ninja.NinjaGears.ToDictionary(ninjaGear => ninjaGear.Gear.Category, ninjaGear =>
                {
                    var gear = ninjaGear.Gear;

                    return new DetailsModel.Gear
                    {
                        Name = gear.Name,
                        Gold = gear.Gold,
                        Agility = gear.Agility,
                        Intelligence = gear.Intelligence,
                        Strength = gear.Strength,
                    };
                })
            };

            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost, ActionName("Create")]
        public async Task<IActionResult> CreatePost(CreateModel createModel)
        {
            if (ModelState.IsValid)
            {
                var ninja = new Ninja
                {
                    Name = createModel.Name,
                    Gold = 400
                };

                if (await _ninjaRepository.Create(ninja))
                {
                    return RedirectToAction(nameof(Index));
                }

                ModelState.AddModelError("", "The ninja could not be created.");
            }

            return View(createModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ninja = await _ninjaRepository.Get(id.Value);

            if (ninja == null)
            {
                return NotFound();
            }

            var model = new EditModel
            {
                Id = ninja.Id,
                Name = ninja.Name,
            };

            return View(model);
        }

        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditPost(EditModel editModel)
        {
            if (ModelState.IsValid)
            {
                var ninja = await _ninjaRepository.Get(editModel.Id);

                if (ninja == null)
                {
                    ModelState.AddModelError("", "The ninja does not exists");
                    return View(editModel);
                }

                ninja.Name = editModel.Name;

                if (await _ninjaRepository.Update(ninja))
                {
                    return RedirectToAction(nameof(Index));
                }

                ModelState.AddModelError("", "The ninja could not be edited.");
            }

            return View(editModel);
        }

        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ninja = await _ninjaRepository.Get(id.Value);

            if (ninja == null)
            {
                return NotFound();
            }

            var model = new DeleteModel
            {
                Id = ninja.Id,
                Name = ninja.Name,
                Gold = ninja.Gold,
                Gears = ninja.NinjaGears.Select(ninjaGear => ninjaGear.Gear.Name)
            };

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] = "Delete failed. Try again, and if the problem persists see your system administrator.";
            }

            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ninja = await _ninjaRepository.Get(id);

            if (ninja == null)
            {
                return RedirectToAction(nameof(Index));
            }

            ninja.NinjaGears.Clear();
            if (await _ninjaRepository.Delete(ninja))
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Delete), new {id, saveChangesError = true});
        }

        public async Task<IActionResult> Clear(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ninja = await _ninjaRepository.Get(id.Value);

            if (ninja == null)
            {
                return NotFound();
            }

            var model = new ClearModel
            {
                Id = ninja.Id,
                Name = ninja.Name,
                Gold = ninja.Gold,
                Gears = ninja.NinjaGears.Select(ninjaGear => new ClearModel.Gear
                {
                    Name = ninjaGear.Gear.Name,
                    Gold = ninjaGear.Gear.Gold
                })
            };

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] = "Could not clear inventory. Try again, and if the problem persists see your system administrator.";
            }

            return View(model);
        }

        [HttpPost, ActionName("Clear")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClearConfirmed(int id)
        {
            var ninja = await _ninjaRepository.Get(id);

            if (ninja == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var addedGold = ninja.NinjaGears.Sum(ninjaGear => ninjaGear.Gear.Gold);

            ninja.Gold += addedGold;
            ninja.NinjaGears.Clear();

            if (await _ninjaRepository.Update(ninja))
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Clear), new {id, saveChangesError = true});
        }
    }
}

NinjaManager.Web/Controllers/ShopController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NinjaManager.Data.Models;
using NinjaManager.Data.Repositories;
using NinjaManager.Web.Models.Shop;

namespace NinjaManager.Web.Controllers
{
    [Route("/Ninjas/Shop/{ninjaId:int}/{action=Index}/{id?}")]
    public class ShopController : Controller
    {
        private readonly NinjaRepository _ninjaRepository;
        private readonly GearsRepository _gearsRepository;

        public ShopController(NinjaRepository ninjaRepository, GearsRepository gearsRepository)
        {
            _ninjaRepository = ninjaRepository;
            _gearsRepository = gearsRepository;
        }

        // GET
        public async Task<IActionResult> Index(int ninjaId, Gear.GearCategory? category)
        {
            var ninja = await _ninjaRepository.Get(ninjaId);

            if (ninja == null)
            {
                return NotFound();
            }

            var gears = await _gearsRepository.GetAll();

            var model = new IndexModel
            {
                Category = category,
                Ninja = new NinjaModel
                {
                    Id = ninja.Id,
                    Name = ninja.Name,
                    Gold = ninja.Gold
                },
                Gears = gears.GroupBy(gear => gear.Category).ToDictionary(grouping => grouping.Key, grouping => grouping.Select(gear => new IndexModel.Gear
                {
                    Id = gear.Id,
                    Name = gear.Name,
                    Gold = gear.Gold,
                    Agility = gear.Agility,
                    Intelligence = gear.Intelligence,
                    Strength = gear.Strength,
                    State = GetGearState(ninja, gear, grouping)
                }))
            };

            return View(model);
        }

        public async Task<IActionResult> Buy(int ninjaId, int? id, bool? saveChangesError = false)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var ninja = await _ninjaRepository.Get(ninjaId);

            var gear = await _gearsRepository.Get(id.Value);

            if (ninja == null || gear == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] = "Purchase failed. Try again, and if the problem persists see your system administrator.";
            }
            else if (ninja.NinjaGears.Select(ninjaGear => ninjaGear.Gear.Category).Contains(gear.Category))
            {
                ViewData["ErrorMessage"] = $"You already own a {gear.Category}.";
            }
            else if (ninja.Gold < gear.Gold)
            {
                ViewData["ErrorMessage"] = "You dont have enough money to buy this.";
            }

            var model = new BuySellModel
            {
                Ninja = new NinjaModel
                {
                    Id = ninja.Id,
                    Name = ninja.Name,
                    Gold = ninja.Gold
                },
                Gear = new BuySellModel.GearModel
                {
                    Id = gear.Id,
                    Name = gear.Name,
                    Gold = gear.Gold
                }
            };

            return View(model);
        }

        [HttpPost, ActionName("Buy")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BuyConfirmed(int ninjaId, int id)
        {
            var ninja = await _ninjaRepository.Get(ninjaId);

            var gear = await _gearsRepository.Get(id);

            if (ninja == null || gear == null)
            {
                return RedirectToAction(nameof(Index), new {ninjaId});
            }

            if (ninja.NinjaGears.Select(ninjaGear => ninjaGear.Gear.Category).Contains(gear.Category) || ninja.Gold < gear.Gold)
            {
                return RedirectToAction(nameof(Buy), new {ninjaId, id, saveChangesError = true});
            }

            ninja.Gold -= gear.Gold;
            ninja.NinjaGears.Add(new NinjaGear
            {
                GearId = gear.Id
            });

            if (await _ninjaRepository.Update(ninja))
            {
                return RedirectToAction(nameof(Index), new {ninjaId});
            }

            return RedirectToAction(nameof(Buy), new {ninjaId, id, saveChangesError = true});
        }

        public async Task<IActionResult> Sell(int ninjaId, int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ninja = await _ninjaRepository.Get(ninjaId);

            if (ninja == null)
            {
                return NotFound();
            }

            var ninjaGear = ninja.NinjaGears.FirstOrDefault(ninjaGear1 => ninjaGear1.GearId == id);

            if (ninjaGear == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] = "Sell failed. Try again, and if the problem persists see your system administrator.";
            }

            return View(new BuySellModel
            {
                Ninja = new NinjaModel
                {
                    Id = ninja.Id,
                    Name = ninja.Name,
                    Gold = ninja.Gold
                },
                Gear = new BuySellModel.GearModel
                {
                    Id = ninjaGear.Gear.Id,
                    Name = ninjaGear.Gear.Name,
                    Gold = ninjaGear.Gear.Gold
                }
            });
        }

        [HttpPost, ActionName("Sell")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SellConfirmed(int ninjaId, int id)
        {
            var ninja = await _ninjaRepository.Get(ninjaId);

            if (ninja == null)
            {
                return RedirectToAction(nameof(Index), new {ninjaId});
            }

            var ninjaGear = ninja.NinjaGears.FirstOrDefault(ninjaGear1 => ninjaGear1.GearId == id);

            if (ninjaGear == null)
            {
                return RedirectToAction(nameof(Sell), new {ninjaId, id, saveChangesError = true});
            }

            ninja.Gold += ninjaGear.Gear.Gold;
            ninja.NinjaGears.Remove(ninjaGear);

            if (await _ninjaRepository.Update(ninja))
            {
                return RedirectToAction(nameof(Index), new {ninjaId});
            }

            return RedirectToAction(nameof(Sell), new {ninjaId, id, saveChangesError = true});
        }

        private IndexModel.Gear.GearState GetGearState(Ninja ninja, Gear gear, IEnumerable<Gear> otherGears)
        {
            if (ninja.NinjaGears.Exists(ninjaGear => ninjaGear.GearId == gear.Id))
            {
                return IndexModel.Gear.GearState.Bought;
            }

            if (ninja.NinjaGears.Select(ninjaGear => ninjaGear.GearId).Intersect(otherGears.Select(gear1 => gear1.Id)).Any())
            {
                return IndexModel.Gear.GearState.OwnsCategory;
            }

            if (ninja.Gold < gear.Gold)
            {
                return IndexModel.Gear.GearState.Expensive;
            }

            return IndexModel.Gear.GearState.Available;
        }
    }
}

NinjaManager.Web/Views/Ninjas/Clear.cshtml
@using NinjaManager.Web.Models.Ninjas

@model ClearModel

@{
    ViewBag.Title = $"Clear {Model.Name}";
}

<h1>Clear Inventory</h1>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h3>Are you sure you want to clear this ninja's inventory?</h3>
<div>
    <h4>Ninja</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gold)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gold)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gears)
        </dt>
        <dd class="col-sm-10">
            <ul>
                @foreach (var gear in Model.Gears)
                {
                    <li>
                        @gear.Name: @gear.Gold
                    </li>
                }
            </ul>
        </dd>
    </dl>

    <form asp-action="Clear">
        <input type="hidden" asp-for="Id"/>
        <input type="submit" value="Clear" class="btn btn-warning"/> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

NinjaManager.Web/Views/Ninjas/Create.cshtml
@using NinjaManager.Web.Models.Ninjas

@model CreateModel

@{
    ViewBag.Title = "Create";
}

<h1>Create</h1>

<h4>Ninja</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

NinjaManager.Web/Views/Ninjas/Delete.cshtml
@using NinjaManager.Web.Models.Ninjas

@model DeleteModel

@{
    ViewBag.Title = $"Delete {Model.Name}";
}

<h1>Delete</h1>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h3>Are you sure you want to delete this ninja?</h3>
<div>
    <h4>Ninja</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gold)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gold)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gears)
        </dt>
        <dd class="col-sm-10">
            @string.Join(", ", Model.Gears)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id"/>
        <input type="submit" value="Delete" class="btn btn-danger"/> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

NinjaManager.Web/Views/Ninjas/Details.cshtml
@using NinjaManager.Data.Models
@using NinjaManager.Web.Models.Ninjas

@model DetailsModel

@{
    ViewBag.Title = Model.Name;
}

<h1>@Model.Name</h1>

<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Gold)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Gold)
    </dd>
</dl>
<dl class="row">
    <dt class="col-sm-2">Total Strength</dt>
    <dd class="col-sm-10">
        @Model.Gears.Sum(pair => pair.Value.Strength)
    </dd>
    <dt class="col-sm-2">Total Agility</dt>
    <dd class="col-sm-10">
        @Model.Gears.Sum(pair => pair.Value.Agility)
    </dd>
    <dt class="col-sm-2">Total Intelligence</dt>
    <dd class="col-sm-10">
        @Model.Gears.Sum(pair => pair.Value.Intelligence)
    </dd>
</dl>
<dl class="row">
    <dt class="col-sm-2">Gear Value</dt>
    <dd class="col-sm-10">
        @Model.Gears.Sum(pair => pair.Value.Gold)
    </dd>
</dl>

<div class="row flex">
    <div class="col-sm-4">
        <partial name="_NinjaGear" model="@(Model.GetGear(Gear.GearCategory.Head))"/>
        <br/>
        <partial name="_NinjaGear" model="@(Model.GetGear(Gear.GearCategory.Hand))"/>
        <br/>
        <partial name="_NinjaGear" model="@(Model.GetGear(Gear.GearCategory.Feet))"/>
        <br/>
    </div>
    <div class="col-sm-4 text-center">
        <p>
            <img style="max-width: 70%;" src="/img/ninja.png" alt="Ninja"/>
        </p>
    </div>
    <div class="col-sm-4">
        <partial name="_NinjaGear" model="@(Model.GetGear(Gear.GearCategory.Necklace))"/>
        <br/>
        <partial name="_NinjaGear" model="@(Model.GetGear(Gear.GearCategory.Chest))"/>
        <br/>
        <partial name="_NinjaGear" model="@(Model.GetGear(Gear.GearCategory.Ring))"/>
        <br/>
    </div>
</div>

NinjaManager.Web/Views/Ninjas/Edit.cshtml
@using NinjaManager.Web.Models.Ninjas

@model EditModel

@{
    ViewBag.Title = $"Edit {Model.Name}";
}

<h1>Edit</h1>

<h4>Ninja</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

NinjaManager.Web/Views/Ninjas/Index.cshtml
@using NinjaManager.Web.Models.Ninjas

@model IndexModel

@{
    ViewBag.Title = "Ninjas";
}

<h1>@ViewBag.Title</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="row">
    <table class="table">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ninjas.FirstOrDefault().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ninjas.FirstOrDefault().Gold)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ninjas.FirstOrDefault().Gears)
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var ninja in Model.Ninjas)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => ninja.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => ninja.Gold)
                </td>
                <td>
                    @String.Join(", ", ninja.Gears)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@ninja.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@ninja.Id">Details</a> |
                    <a asp-action="Clear" asp-route-id="@ninja.Id">Clear Inventory</a> |
                    <a asp-controller="Shop" asp-route-ninjaId="@ninja.Id">Shop</a> |
                    <a asp-action="Delete" asp-route-id="@ninja.Id">Delete</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

NinjaManager.Web/Views/Ninjas/_NinjaGear.cshtml
@model KeyValuePair<NinjaManager.Data.Models.Gear.GearCategory, NinjaManager.Web.Models.Ninjas.DetailsModel.Gear>

<div class="card">
    <span class="card-header">
        @Model.Key: @(Model.Value?.Name ?? "None")
    </span>
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-6">Strength</dt>
            <dd class="col-sm-6">
                @(Model.Value?.Strength ?? 0)
            </dd>
            <dt class="col-sm-6">Agility</dt>
            <dd class="col-sm-6">
                @(Model.Value?.Agility ?? 0)
            </dd>
            <dt class="col-sm-6">Intelligence</dt>
            <dd class="col-sm-6">
                @(Model.Value?.Intelligence ?? 0)
            </dd>
        </dl>
    </div>
</div>